<?php
    require_once("xml2json.php");
//<br>
    // Filename from where XML contents are to be read.
    $testXmlFile = "";
//<br>
    // Read the filename from the command line.
    if ($argc <= 1) {
        print("Please provide the XML filename as a command-line argument:\n");
        print("php -f xml2json_test.php test1.xml\n");
        return;
    } else {
        $testXmlFile = $argv[1];
    }
//<br>
    //Read the XML contents from the input file.
    file_exists($testXmlFile) or die('Could not find file ' . $testXmlFile);
    $xmlStringContents = file_get_contents($testXmlFile);
//<br>
    $jsonContents = "";
    // Convert it to JSON now.
    // xml2json simply takes a String containing XML contents as input.
    $jsonContents = xml2json::transformXmlStringToJson($xmlStringContents);
//<br>
    echo("JSON formatted output generated by xml2json:\n\n");
    echo($jsonContents);
?>
